spring:
  datasource:
    url: jdbc:h2:mem:maindb
#  sql:
#    init:
#      mode: always
#      data-locations: data.sql
#      schema-locations: schema.sql
  jpa:
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: health, metrics, logfile
  endpoint:
    health:
      show-details: always
logging:
  file:
    name: logs/app.log