server:
  port: 8080

#spring:
#  datasource:
#    url: jdbc:h2:mem:maindb
#  sql:
#    init:
#      mode: always
#      data-locations: data.sql
#      schema-locations: schema.sql
#  jpa:
#    open-in-view: false
#    generate-ddl: false
#    hibernate:
#      ddl-auto: none
#    show-sql: true
#
spring:
  r2dbc:
    url: r2dbc:h2:mem:///testdb
    username: user
    password: password
    pool:
      enabled: true
  sql:
    init:
      mode: always
h2:
  console:
    enabled: true